-- Taller 3

-- Se debe hacer uso de las siguientes tablas:
-- - PREMIERL_Matches;
-- - PREMIERL_Teams;
-- - PREMIERL_Actions;
-- - PREMIERL_Players;

-- Obtener los esquemas de cada tabla
SELECT
    *
FROM
    PREMIERL_MATCHES;

SELECT
    *
FROM
    PREMIERL_TEAMS;

SELECT
    *
FROM
    PREMIERL_ACTIONS;

SELECT
    *
FROM
    PREMIERL_PLAYERS;

-- Esquema Premierl_actions:

-- Name	Null?	Type
-- PLAYERID	NOT NULL	NUMBER(11)
-- MATCHID	NOT NULL	NUMBER(11)
-- TEAMID		NUMBER(11)
-- FIRSTGOAL		NUMBER(11)
-- WINNINGGOAL		NUMBER(11)
-- SHOTSONTARGETINCGOALS		NUMBER(11)
-- SAVESMADE		NUMBER(11)
-- TIMEPLAYED		NUMBER(11)
-- POSITIONID		NUMBER(11)
-- STARTS		NUMBER(11)
-- SUBSTITUTEON		NUMBER(11)
-- SUBSTITUTEOFF		NUMBER(11)
-- GOALS		NUMBER(11)
-- SHOTSOFFTARGETINCWOODWORK		NUMBER(11)
-- BLOCKEDSHOTS		NUMBER(11)
-- PENALTIESTAKEN		NUMBER(11)
-- PENALTYGOALS		NUMBER(11)
-- PENALTIESSAVED		NUMBER(11)
-- PENALTIESOFFTARGET		NUMBER(11)
-- PENALTIESNOTSCORED		NUMBER(11)
-- DIRECTFREEKICKGOALS		NUMBER(11)
-- DIRECTFREEKICKONTARGET		NUMBER(11)
-- DIRECTFREEKICKOFFTARGET		NUMBER(11)
-- BLOCKEDDIRECTFREEKICK		NUMBER(11)
-- GOALSFROMINSIDEBOX		NUMBER(11)
-- SHOTSONFROMINSIDEBOX		NUMBER(11)
-- SHOTSOFFFROMINSIDEBOX		NUMBER(11)
-- BLOCKEDSHOTSFROMINSIDEBOX		NUMBER(11)
-- GOALSFROMOUTSIDEBOX		NUMBER(11)
-- SHOTSONTARGETOUTSIDEBOX		NUMBER(11)
-- SHOTSOFFTARGETOUTSIDEBOX		NUMBER(11)
-- BLOCKEDSHOTSOUTSIDEBOX		NUMBER(11)
-- HEADEDGOALS		NUMBER(11)
-- HEADEDSHOTSONTARGET		NUMBER(11)
-- HEADEDSHOTSOFFTARGET		NUMBER(11)
-- HEADEDBLOCKEDSHOTS		NUMBER(11)
-- LEFTFOOTGOALS		NUMBER(11)
-- LEFTFOOTSHOTSONTARGET		NUMBER(11)
-- LEFTFOOTSHOTSOFFTARGET		NUMBER(11)
-- LEFTFOOTBLOCKEDSHOTS		NUMBER(11)
-- RIGHTFOOTGOALS		NUMBER(11)
-- RIGHTFOOTSHOTSONTARGET		NUMBER(11)
-- RIGHTFOOTSHOTSOFFTARGET		NUMBER(11)
-- RIGHTFOOTBLOCKEDSHOTS		NUMBER(11)
-- OTHERGOALS		NUMBER(11)
-- OTHERSHOTSONTARGET		NUMBER(11)
-- OTHERSHOTSOFFTARGET		NUMBER(11)
-- OTHERBLOCKEDSHOTS		NUMBER(11)
-- SHOTSCLEAREDOFFLINE		NUMBER(11)
-- SHOTSCLEAREDOFFLINEINSIDEAREA		NUMBER(11)
-- SHOTSCLEAREDOFFLINEOUTSIDEAREA		NUMBER(11)
-- GOALSOPENPLAY		NUMBER(11)
-- GOALSFROMCORNERS		NUMBER(11)
-- GOALSFROMTHROWS		NUMBER(11)
-- GOALSFROMDIRECTFREEKICK		NUMBER(11)
-- GOALSFROMSETPLAY		NUMBER(11)
-- GOALSFROMPENALTIES		NUMBER(11)
-- ATTEMPTSOPENPLAYONTARGET		NUMBER(11)
-- ATTEMPTSFROMCORNERSONTARGET		NUMBER(11)
-- ATTEMPTSFROMTHROWSONTARGET		NUMBER(11)
-- ATTEMPTSFROMDIRECTFREEKICKONTARGET		NUMBER(11)
-- ATTEMPTSFROMSETPLAYONTARGET		NUMBER(11)
-- ATTEMPTSFROMPENALTIESONTARGET		NUMBER(11)
-- ATTEMPTSOPENPLAYOFFTARGET		NUMBER(11)
-- ATTEMPTSFROMCORNERSOFFTARGET		NUMBER(11)
-- ATTEMPTSFROMTHROWSOFFTARGET		NUMBER(11)
-- ATTEMPTSFROMDIRECTFREEKICKOFFTARGET		NUMBER(11)
-- ATTEMPTSFROMSETPLAYOFFTARGET		NUMBER(11)
-- ATTEMPTSFROMPENALTIESOFFTARGET		NUMBER(11)
-- GOALSASASUBSTITUTE		NUMBER(11)
-- TOTALSUCCESSFULPASSESALL		NUMBER(11)
-- TOTALUNSUCCESSFULPASSESALL		NUMBER(11)
-- ASSISTS		NUMBER(11)
-- KEYPASSES		NUMBER(11)
-- TOTALSUCCESSFULPASSESEXCLCROSSESCORNERS		NUMBER(11)
-- TOTALUNSUCCESSFULPASSESEXCLCROSSESCORNERS		NUMBER(11)
-- SUCCESSFULPASSESOWNHALF		NUMBER(11)
-- UNSUCCESSFULPASSESOWNHALF		NUMBER(11)
-- SUCCESSFULPASSESOPPOSITIONHALF		NUMBER(11)
-- UNSUCCESSFULPASSESOPPOSITIONHALF		NUMBER(11)
-- SUCCESSFULPASSESDEFENSIVETHIRD		NUMBER(11)
-- UNSUCCESSFULPASSESDEFENSIVETHIRD		NUMBER(11)
-- SUCCESSFULPASSESMIDDLETHIRD		NUMBER(11)
-- UNSUCCESSFULPASSESMIDDLETHIRD		NUMBER(11)
-- SUCCESSFULPASSESFINALTHIRD		NUMBER(11)
-- UNSUCCESSFULPASSESFINALTHIRD		NUMBER(11)
-- SUCCESSFULSHORTPASSES		NUMBER(11)
-- UNSUCCESSFULSHORTPASSES		NUMBER(11)
-- SUCCESSFULLONGPASSES		NUMBER(11)
-- UNSUCCESSFULLONGPASSES		NUMBER(11)
-- SUCCESSFULFLICKONS		NUMBER(11)
-- UNSUCCESSFULFLICKONS		NUMBER(11)
-- SUCCESSFULCROSSESCORNERS		NUMBER(11)
-- UNSUCCESSFULCROSSESCORNERS		NUMBER(11)
-- CORNERSTAKENINCLSHORTCORNERS		NUMBER(11)
-- CORNERSCONCEDED		NUMBER(11)
-- SUCCESSFULCORNERSNUMBEROBOX		NUMBER(11)
-- UNSUCCESSFULCORNERSNUMBEROBOX		NUMBER(11)
-- SHORTCORNERS		NUMBER(11)
-- THROWINSTOOWNPLAYER		NUMBER(11)
-- THROWINSTOOPPOSITIONPLAYER		NUMBER(11)
-- SUCCESSFULDRIBBLES		NUMBER(11)
-- UNSUCCESSFULDRIBBLES		NUMBER(11)
-- SUCCESSFULCROSSESCORNERSLEFT		NUMBER(11)
-- UNSUCCESSFULCROSSESCORNERSLEFT		NUMBER(11)
-- SUCCESSFULCROSSESLEFT		NUMBER(11)
-- UNSUCCESSFULCROSSESLEFT		NUMBER(11)
-- SUCCESSFULCORNERSLEFT		NUMBER(11)
-- UNSUCCESSFULCORNERSLEFT		NUMBER(11)
-- SUCCESSFULCROSSESCORNERSRIGHT		NUMBER(11)
-- UNSUCCESSFULCROSSESCORNERSRIGHT		NUMBER(11)
-- SUCCESSFULCROSSESRIGHT		NUMBER(11)
-- UNSUCCESSFULCROSSESRIGHT		NUMBER(11)
-- SUCCESSFULCORNERSRIGHT		NUMBER(11)
-- UNSUCCESSFULCORNERSRIGHT		NUMBER(11)
-- SUCCESSFULLONGBALLS		NUMBER(11)
-- UNSUCCESSFULLONGBALLS		NUMBER(11)
-- SUCCESSFULLAYOFFS		NUMBER(11)
-- UNSUCCESSFULLAYOFFS		NUMBER(11)
-- THROUGHBALL		NUMBER(11)
-- SUCCESSFULCROSSESCORNERSNUMBERHEAIR		NUMBER(11)
-- UNSUCCESSFULCROSSESCORNERSNUMBERHEAIR		NUMBER(11)
-- SUCCESSFULCROSSESNUMBERHEAIR		NUMBER(11)
-- UNSUCCESSFULCROSSESNUMBERHEAIR		NUMBER(11)
-- SUCCESSFULOPENPLAYCROSSES		NUMBER(11)
-- UNSUCCESSFULOPENPLAYCROSSES		NUMBER(11)
-- TOUCHES		NUMBER(11)
-- GOALASSISTCORNER		NUMBER(11)
-- GOALASSISTFREEKICK		NUMBER(11)
-- GOALASSISTTHROWIN		NUMBER(11)
-- GOALASSISTGOALKICK		NUMBER(11)
-- GOALASSISTSETPIECE		NUMBER(11)
-- KEYCORNER		NUMBER(11)
-- KEYFREEKICK		NUMBER(11)
-- KEYTHROWIN		NUMBER(11)
-- KEYGOALKICK		NUMBER(11)
-- KEYSETPIECES		NUMBER(11)
-- DUELSWON		NUMBER(11)
-- DUELSLOST		NUMBER(11)
-- AERIALDUELSWON		NUMBER(11)
-- AERIALDUELSLOST		NUMBER(11)
-- GROUNDDUELSWON		NUMBER(11)
-- GROUNDDUELSLOST		NUMBER(11)
-- TACKLESWON		NUMBER(11)
-- TACKLESLOST		NUMBER(11)
-- LASTMANTACKLE		NUMBER(11)
-- TOTALCLEARANCES		NUMBER(11)
-- HEADEDCLEARANCES		NUMBER(11)
-- OTHERCLEARANCES		NUMBER(11)
-- CLEARANCESOFFTHELINE		NUMBER(11)
-- BLOCKS		NUMBER(11)
-- INTERCEPTIONS		NUMBER(11)
-- RECOVERIES		NUMBER(11)
-- TOTALFOULSCONCEDED		NUMBER(11)
-- FOULSCONCEDEDEXCHANDBALLSPENS		NUMBER(11)
-- TOTALFOULSWON		NUMBER(11)
-- FOULSWONINDANGERAREAINCPENS		NUMBER(11)
-- FOULSWONNOTINDANGERAREA		NUMBER(11)
-- FOULWONPENALTY		NUMBER(11)
-- HANDBALLSCONCEDED		NUMBER(11)
-- PENALTIESCONCEDED		NUMBER(11)
-- OFFSIDES		NUMBER(11)
-- YELLOWCARDS		NUMBER(11)
-- REDCARDS		NUMBER(11)
-- GOALSCONCEDED		NUMBER(11)
-- GOALSCONCEDEDINSIDEBOX		NUMBER(11)
-- GOALSCONCEDEDOUTSIDEBOX		NUMBER(11)
-- SAVESMADEFROMINSIDEBOX		NUMBER(11)
-- SAVESMADEFROMOUTSIDEBOX		NUMBER(11)
-- SAVESFROMPENALTY		NUMBER(11)
-- CATCHES		NUMBER(11)
-- PUNCHES		NUMBER(11)
-- DROPS		NUMBER(11)
-- CROSSESNOTCLAIMED		NUMBER(11)
-- GKDISTRIBUTION		NUMBER(11)
-- GKSUCCESSFULDISTRIBUTION		NUMBER(11)
-- GKUNSUCCESSFULDISTRIBUTION		NUMBER(11)
-- CLEANSHEETS		NUMBER(11)
-- TEAMCLEANSHEET		NUMBER(11)
-- ERRORLEADINGTOGOAL		NUMBER(11)
-- ERRORLEADINGTOATTEMPT		NUMBER(11)
-- CHALLENGELOST		NUMBER(11)
-- SHOTSONCONCEDED		NUMBER(11)
-- SHOTSONCONCEDEDINSIDEBOX		NUMBER(11)
-- SHOTSONCONCEDEDOUTSIDEBOX		NUMBER(11)
-- POSITIONINFORMATION		NUMBER(11)
-- TURNOVERS		NUMBER(11)
-- DISPOSSESSED		NUMBER(11)
-- BIGCHANCES		NUMBER(11)
-- BIGCHANCESFACED		NUMBER(11)
-- PASSFORWARD		NUMBER(11)
-- PASSBACKWARD		NUMBER(11)
-- PASSLEFT		NUMBER(11)
-- PASSRIGHT		NUMBER(11)
-- UNSUCCESSFULBALLTOUCH		NUMBER(11)
-- SUCCESSFULBALLTOUCH		NUMBER(11)
-- TAKEONSOVERRUN		NUMBER(11)
-- TOUCHESOPENPLAYFINALTHIRD		NUMBER(11)
-- TOUCHESOPENPLAYOPPBOX		NUMBER(11)
-- TOUCHESOPENPLAYOPPSIXYARDS		NUMBER(11)
-- SHOT_EFF		NUMBER(7,6)
-- PASSES_EFF		NUMBER(7,6)
-- TACKLE_EFF		NUMBER(7,6)
-- DRIBBLE_EFF		NUMBER(7,6)


-- Describe Premierl_matches


-- Name	Null?	Type
-- MATCHID	NOT NULL	NUMBER(11)
-- TEAMHOMEID		NUMBER(11)
-- TEAMAWAYID		NUMBER(11)
-- TEAMHOMEFORMATION		NUMBER(11)
-- TEAMAWAYFORMATION		NUMBER(11)
-- RESULTOFTEAMHOME		NUMBER(11)
-- DATE_		TIMESTAMP(6)

-- Describe Premierl_teams


-- Name	Null?	Type
-- TEAMID	NOT NULL	NUMBER(11)
-- NAME	NOT NULL	VARCHAR2(40)

-- Describe Premierl_players


-- Name	Null?	Type
-- PLAYERID	NOT NULL	NUMBER(11)
-- NAME	NOT NULL	VARCHAR2(100)



--  2) Mostrar los partidos jugados. El resultado debe tener la siguiente información:
-- a. ID del partido.
-- b. Resultado del partido (equipo home) [-1 : lost, 0: tie; 1: won]
-- c. Nombre del equipo local (NO es el id)
-- d. Nombre del equipo visitante (NO es el id)
-- e. Fecha del partido en formato (dd-mm-aaaa).

SELECT
    M.MATCHID,
    CASE
        WHEN M.RESULTOFTEAMHOME = -1 THEN
            'lost'
        WHEN M.RESULTOFTEAMHOME = 0 THEN
            'tie'
        WHEN M.RESULTOFTEAMHOME = 1 THEN
            'won'
        ELSE
            'N/A'
    END           AS RESULT,
    T1.NAME       AS TEAMHOME,
    T2.NAME       AS TEAMAWAY,
    TO_CHAR(M.DATE_,
    'DD-MM-YYYY') AS DATE_
FROM
    JLEON.PREMIERL_MATCHES M
    JOIN JLEON.PREMIERL_TEAMS T1
    ON M.TEAMHOMEID = T1.TEAMID JOIN JLEON.PREMIERL_TEAMS T2
    ON M.TEAMAWAYID = T2.TEAMID;

SELECT
    *
FROM
    JLEON.PREMIERL_MATCHES;

-- Create view

CREATE OR REPLACE VIEW T2_LOPEZ_JUAN_2 AS
    SELECT
        M.MATCHID,
        CASE
            WHEN M.RESULTOFTEAMHOME = -1 THEN
                'lost'
            WHEN M.RESULTOFTEAMHOME = 0 THEN
                'tie'
            WHEN M.RESULTOFTEAMHOME = 1 THEN
                'won'
            ELSE
                'N/A'
        END           AS RESULT,
        T1.NAME       AS TEAMHOME,
        T2.NAME       AS TEAMAWAY,
        TO_CHAR(M.DATE_,
        'DD-MM-YYYY') AS DATE_
    FROM
        JLEON.PREMIERL_MATCHES M
        JOIN JLEON.PREMIERL_TEAMS T1
        ON M.TEAMHOMEID = T1.TEAMID JOIN JLEON.PREMIERL_TEAMS T2
        ON M.TEAMAWAYID = T2.TEAMID;

-- Grant acces to jleon

GRANT SELECT ON T2_LOPEZ_JUAN_2 TO JLEON;

-- 3) Mostrar una lista de la cantidad de partidos ganados por cada equipo siendo local o visitante
-- y ordenar el resultado para mostrar primero los que más partidos ganaron. El resultado
-- debe tener
-- a. Cantidad total de partidos ganados.
-- b. Nombre del equipo.

SELECT
    COUNT(*) AS TOTAL,
    T.NAME
FROM
    JLEON.PREMIERL_MATCHES M
    JOIN JLEON.PREMIERL_TEAMS T
    ON M.TEAMHOMEID = T.TEAMID
WHERE
    M.RESULTOFTEAMHOME = 1
GROUP BY
    T.NAME UNION
    SELECT
        COUNT(*) AS TOTAL,
        T.NAME
    FROM
        JLEON.PREMIERL_MATCHES M
        JOIN JLEON.PREMIERL_TEAMS T
        ON M.TEAMAWAYID = T.TEAMID
    WHERE
        M.RESULTOFTEAMHOME = -1
    GROUP BY
        T.NAME
    ORDER BY
        TOTAL DESC;

-- Create view

CREATE OR REPLACE VIEW T3_LOPEZ_JUAN_3 AS
    SELECT
        COUNT(*) AS TOTAL,
        T.NAME
    FROM
        JLEON.PREMIERL_MATCHES M
        JOIN JLEON.PREMIERL_TEAMS T
        ON M.TEAMHOMEID = T.TEAMID
    WHERE
        M.RESULTOFTEAMHOME = 1
    GROUP BY
        T.NAME UNION
        SELECT
            COUNT(*) AS TOTAL,
            T.NAME
        FROM
            JLEON.PREMIERL_MATCHES M
            JOIN JLEON.PREMIERL_TEAMS T
            ON M.TEAMAWAYID = T.TEAMID
        WHERE
            M.RESULTOFTEAMHOME = -1
        GROUP BY
            T.NAME
        ORDER BY
            TOTAL DESC;

-- Grant acces to jleon

GRANT SELECT ON T3_LOPEZ_JUAN_2 TO JLEON;

-- 4) Seleccione todos los jugadores que solo tienen 1 nombre. Puede ayudarse de funciones
-- como TRIM y como REGEXP_LIKE.

SELECT
    P.PLAYERID,
    P.NAME
FROM
    JLEON.PREMIERL_PLAYERS P
WHERE
    REGEXP_LIKE(TRIM(P.NAME),
    '^[A-Z][a-z]+$',
    'i');

-- Create view

CREATE OR REPLACE VIEW T4_LOPEZ_JUAN_4 AS
    SELECT
        P.PLAYERID,
        P.NAME
    FROM
        JLEON.PREMIERL_PLAYERS P
    WHERE
        REGEXP_LIKE(TRIM(P.NAME),
        '^[A-Z][a-z]+$',
        'i');

-- Grant acces to jleon

GRANT SELECT ON T4_LOPEZ_JUAN_4 TO JLEON;

-- 5) Seleccione el nombre de los jugadores y el tiempo jugado, de aquellos jugadores que
-- tuvieron un tiempo de juego superior a la media de todos los jugadores. (Tenga en cuenta
-- que obtener el promedio total de la tabla es diferente del promedio del tiempo de los
-- jugadores)

SELECT
    P.NAME,
    SUM(A.TIMEPLAYED) AS TOTAL_TIME
FROM
    JLEON.PREMIERL_PLAYERS P
    JOIN JLEON.PREMIERL_ACTIONS A
    ON P.PLAYERID = A.PLAYERID
GROUP BY
    P.NAME
HAVING
    AVG(A.TIMEPLAYED) > (
        SELECT
            AVG(TIMEPLAYED)
        FROM
            JLEON.PREMIERL_ACTIONS
    );

-- Create view

CREATE OR REPLACE VIEW T5_LOPEZ_JUAN_5 AS
    SELECT
        P.NAME,
        SUM(A.TIMEPLAYED) AS TOTAL_TIME
    FROM
        JLEON.PREMIERL_PLAYERS P
        JOIN JLEON.PREMIERL_ACTIONS A
        ON P.PLAYERID = A.PLAYERID
    GROUP BY
        P.NAME
    HAVING
        AVG(A.TIMEPLAYED) > (
            SELECT
                AVG(TIMEPLAYED)
            FROM
                JLEON.PREMIERL_ACTIONS
        );

-- Grant acces to jleon

GRANT SELECT ON T5_LOPEZ_JUAN_5 TO JLEON;

-- 6) Indique la cantidad de jugadores que se encuentran debajo de la media del tiempo jugado
-- y los jugadores que se encuentran sobre la media del tiempo jugado. El resultado debe
-- aparecer en la misma tabla con dos columnas (TOTAL, DESCRIPCION [MAYOR_MEDIA,
-- MENOR_MEDIA])

--  TODO: CHECK THIS ONE
SELECT
    COUNT(*)      AS TOTAL,
    'MAYOR_MEDIA' AS DESCRIPCION
FROM
    JLEON.PREMIERL_PLAYERS P
    JOIN JLEON.PREMIERL_ACTIONS A
    ON P.PLAYERID = A.PLAYERID
HAVING
    AVG(A.TIMEPLAYED) > (
        SELECT
            AVG(TIMEPLAYED)
        FROM
            JLEON.PREMIERL_ACTIONS
    ) UNION
    SELECT
        COUNT(*)      AS TOTAL,
        'MENOR_MEDIA' AS DESCRIPCION
    FROM
        JLEON.PREMIERL_PLAYERS P
        JOIN JLEON.PREMIERL_ACTIONS A
        ON P.PLAYERID = A.PLAYERID
    HAVING
        AVG(A.TIMEPLAYED) < (
            SELECT
                AVG(TIMEPLAYED)
            FROM
                JLEON.PREMIERL_ACTIONS
        );

-- 7) Seleccione el nombre de todos los jugadores del “Aston Villa” sin elementos repetidos.


SELECT
    DISTINCT P.NAME
FROM
    JLEON.PREMIERL_PLAYERS P
    JOIN JLEON.PREMIERL_ACTIONS A
    ON P.PLAYERID = A.PLAYERID JOIN JLEON.PREMIERL_MATCHES M
    ON A.MATCHID = M.MATCHID
    JOIN JLEON.PREMIERL_TEAMS T
    ON M.TEAMHOMEID = T.TEAMID
WHERE
    T.NAME = 'Aston Villa';

-- Create view

CREATE VIEW T7_LOPEZ_JUAN_7 AS
    SELECT
        DISTINCT P.NAME
    FROM
        JLEON.PREMIERL_PLAYERS P
        JOIN JLEON.PREMIERL_ACTIONS A
        ON P.PLAYERID = A.PLAYERID JOIN JLEON.PREMIERL_MATCHES M
        ON A.MATCHID = M.MATCHID
        JOIN JLEON.PREMIERL_TEAMS T
        ON M.TEAMHOMEID = T.TEAMID
    WHERE
        T.NAME = 'Aston Villa';

-- Grant acces to jleon

GRANT SELECT ON T7_LOPEZ_JUAN_7 TO JLEON;

-- 8) Seleccione los partidos que tuvieron penaltis durante el 2011 y en donde no hayan jugado
-- los equipos 'ARSENAL','EVERTON','MANCHESTER CITY' (ya sea como local o como visitante).
-- El resultado deberá contener:
-- a. ID del partido
-- b. Cantidad de penaltis
-- c. Equipo local
-- d. Equipo visitante
-- e. Fecha en formato (dd-mm-aaaa)
-- Ten en cuenta que para saber si hubieron penalties debes saber si

SELECT
    M.MATCHID,
    A.PENALTYGOALS AS PENALTIES,
    T1.NAME        AS TEAMHOME,
    T2.NAME        AS TEAMAWAY,
    TO_CHAR(M.DATE_,
    'DD-MM-YYYY')  AS DATE_
FROM
    JLEON.PREMIERL_MATCHES M
    JOIN JLEON.PREMIERL_ACTIONS A
    ON M.MATCHID = A.MATCHID JOIN JLEON.PREMIERL_TEAMS T1
    ON M.TEAMHOMEID = T1.TEAMID
    JOIN JLEON.PREMIERL_TEAMS T2
    ON M.TEAMAWAYID = T2.TEAMID
HAVING
    M.DATE_ BETWEEN TO_DATE('01-01-2011', 'DD-MM-YYYY')
    AND TO_DATE('31-12-2011', 'DD-MM-YYYY')
    AND UPPER(T1.NAME) NOT IN ('ARSENAL', 'EVERTON', 'MANCHESTER CITY')
    AND UPPER(T2.NAME) NOT IN ('ARSENAL', 'EVERTON', 'MANCHESTER CITY')
GROUP BY
    M.MATCHID, A.PENALTYGOALS, T1.NAME, T2.NAME, M.DATE_;

-- Create view

CREATE VIEW T8_LOPEZ_JUAN_8 AS
    SELECT
        M.MATCHID,
        A.PENALTYGOALS AS PENALTIES,
        T1.NAME        AS TEAMHOME,
        T2.NAME        AS TEAMAWAY,
        TO_CHAR(M.DATE_,
        'DD-MM-YYYY')  AS DATE_
    FROM
        JLEON.PREMIERL_MATCHES M
        JOIN JLEON.PREMIERL_ACTIONS A
        ON M.MATCHID = A.MATCHID JOIN JLEON.PREMIERL_TEAMS T1
        ON M.TEAMHOMEID = T1.TEAMID
        JOIN JLEON.PREMIERL_TEAMS T2
        ON M.TEAMAWAYID = T2.TEAMID
    HAVING
        M.DATE_ BETWEEN TO_DATE('01-01-2011', 'DD-MM-YYYY')
        AND TO_DATE('31-12-2011', 'DD-MM-YYYY')
        AND UPPER(T1.NAME) NOT IN ('ARSENAL', 'EVERTON', 'MANCHESTER CITY')
        AND UPPER(T2.NAME) NOT IN ('ARSENAL', 'EVERTON', 'MANCHESTER CITY')
    GROUP BY
        M.MATCHID, A.PENALTYGOALS, T1.NAME, T2.NAME, M.DATE_;

-- Grant acces to jleon

GRANT SELECT ON T8_LOPEZ_JUAN_8 TO JLEON;

-- 9) Seleccione los jugadores que tuvieron participación en el partido con mas goles durante el
-- primer semestre del 2012. Puede usar la función ROWNUM.

SELECT
    P.NAME
FROM
    JLEON.PREMIERL_PLAYERS P
    JOIN JLEON.PREMIERL_ACTIONS A
    ON P.PLAYERID = A.PLAYERID JOIN JLEON.PREMIERL_MATCHES M
    ON A.MATCHID = M.MATCHID
WHERE
    M.MATCHID = (
        SELECT
            M.MATCHID
        FROM
            JLEON.PREMIERL_MATCHES M
            JOIN JLEON.PREMIERL_ACTIONS A
            ON M.MATCHID = A.MATCHID
        WHERE
            M.DATE_ BETWEEN TO_DATE('01-01-2012', 'DD-MM-YYYY')
            AND TO_DATE('30-06-2012', 'DD-MM-YYYY')
        GROUP BY
            M.MATCHID, A.GOALS
        ORDER BY
            A.GOALS DESC FETCH FIRST 1 ROWS ONLY
    );

-- Create view

CREATE VIEW T9_LOPEZ_JUAN_9 AS
    SELECT
        P.NAME
    FROM
        JLEON.PREMIERL_PLAYERS P
        JOIN JLEON.PREMIERL_ACTIONS A
        ON P.PLAYERID = A.PLAYERID JOIN JLEON.PREMIERL_MATCHES M
        ON A.MATCHID = M.MATCHID
    WHERE
        M.MATCHID = (
            SELECT
                M.MATCHID
            FROM
                JLEON.PREMIERL_MATCHES M
                JOIN JLEON.PREMIERL_ACTIONS A
                ON M.MATCHID = A.MATCHID
            WHERE
                M.DATE_ BETWEEN TO_DATE('01-01-2012', 'DD-MM-YYYY')
                AND TO_DATE('30-06-2012', 'DD-MM-YYYY')
            GROUP BY
                M.MATCHID, A.GOALS
            ORDER BY
                A.GOALS DESC FETCH FIRST 1 ROWS ONLY
        );

-- Grant acces to jleon

GRANT SELECT ON T9_LOPEZ_JUAN_9 TO JLEON;

-- 10) Describa el enunciado de una consulta y desarróllela, debe involucrar:
-- a. Subqueries anidados.
-- b. Agrupaciones.
-- c. Operaciones sobre campos string.
-- d. Operaciones sobre campos de fecha.
-- e. Operaciones sobre conjuntos (in, not in).

-- La consulta que cumple todos estos parametros seria:

-- Seleccione los jugadores que no hayan jugado en el partido con mas goles durante el primer
-- semestre del 2012.

SELECT
    P.NAME
FROM
    JLEON.PREMIERL_PLAYERS P
WHERE
    P.PLAYERID NOT IN (
        SELECT
            A.PLAYERID
        FROM
            JLEON.PREMIERL_ACTIONS A
            JOIN JLEON.PREMIERL_MATCHES M
            ON A.MATCHID = M.MATCHID
        WHERE
            M.MATCHID = (
                SELECT
                    M.MATCHID
                FROM
                    JLEON.PREMIERL_MATCHES M
                    JOIN JLEON.PREMIERL_ACTIONS A
                    ON M.MATCHID = A.MATCHID
                WHERE
                    M.DATE_ BETWEEN TO_DATE('01-01-2012', 'DD-MM-YYYY')
                    AND TO_DATE('30-06-2012', 'DD-MM-YYYY')
                GROUP BY
                    M.MATCHID, A.GOALS
                ORDER BY
                    A.GOALS DESC FETCH FIRST 1 ROWS ONLY
            )
    );

-- Create view

CREATE VIEW T10_LOPEZ_JUAN_10 AS
    SELECT
        P.NAME
    FROM
        JLEON.PREMIERL_PLAYERS P
    WHERE
        P.PLAYERID NOT IN (
            SELECT
                A.PLAYERID
            FROM
                JLEON.PREMIERL_ACTIONS A
                JOIN JLEON.PREMIERL_MATCHES M
                ON A.MATCHID = M.MATCHID
            WHERE
                M.MATCHID = (
                    SELECT
                        M.MATCHID
                    FROM
                        JLEON.PREMIERL_MATCHES M
                        JOIN JLEON.PREMIERL_ACTIONS A
                        ON M.MATCHID = A.MATCHID
                    WHERE
                        M.DATE_ BETWEEN TO_DATE('01-01-2012', 'DD-MM-YYYY')
                        AND TO_DATE('30-06-2012', 'DD-MM-YYYY')
                    GROUP BY
                        M.MATCHID, A.GOALS
                    ORDER BY
                        A.GOALS DESC FETCH FIRST 1 ROWS ONLY
                )
        );

-- Grant acces to jleon

GRANT SELECT ON T10_LOPEZ_JUAN_10 TO JLEON;

-- PARTE 2